"""
chat.py - GLM Chatbot engine with Gemma fallback.
Handles all conversational logic including date-based memory queries.

Primary: GLM (z.ai / BigModel)
Fallback: Gemma 4 (Google AI Studio) — kicks in on rate limit (429) or other API errors.

SHARED by both in-app chat and hardware chat modules.
"""
import os
from datetime import datetime, timedelta
from typing import List, Optional
from openai import AsyncOpenAI

from database import get_chat_history, save_chat_message, get_memories_by_date, get_recent_memories

# ============================================================
# CLIENTS
# ============================================================

# Primary: GLM Client (z.ai / BigModel)
glm_client = AsyncOpenAI(
    api_key=os.getenv("GLM_API_KEY"),
    base_url="https://open.bigmodel.cn/api/paas/v4"
)

# Fallback: Google GenerativeAI (Gemma 4) — using existing google-generativeai package
_gemma_model = None


def _get_gemma_model():
    """Lazy-init Gemma model using existing google-generativeai package."""
    global _gemma_model
    if _gemma_model is None:
        import google.generativeai as genai
        genai.configure(api_key=os.getenv("GOOGLE_AI_STUDIO_KEY"))
        _gemma_model = genai.GenerativeModel("gemma-4-26b-a4b-it")
    return _gemma_model

SYSTEM_PROMPT = """You are EyeDentify, an AI assistant for blind and visually impaired users.
You are helpful, concise, and safety-conscious. Key guidelines:

1. Always prioritize safety - warn about hazards proactively.
2. Use descriptive spatial language (left/right/near/far).
3. Be VERY concise - respond in 1-2 short sentences maximum. Screen readers will read your responses aloud.
4. NEVER output your reasoning, thought process, or internal monologue. Output ONLY the final user-facing response.
5. Do NOT use bullet points, numbered lists, or options like "Option 1/Option 2". Just answer directly.
6. When referencing memories/images the user has captured, use past tense.
7. If the user asks about what they've seen before, reference their memory logs.
8. Be warm and supportive. Your user may rely on you for independence."""


# def _strip_reasoning(text: str) -> str:
#     """Remove leaked chain-of-thought / reasoning from model output."""
#     import re
#     original = text

#     # Remove patterns like "* Previous context:", "* User just...", "* This could mean:"
#     lines = text.split('\n')
#     cleaned = []
#     for line in lines:
#         stripped = line.strip()
#         # Skip lines that look like internal reasoning
#         if not stripped:
#             continue
#         if stripped.startswith(('* ')) or stripped.startswith('*'):
#             lower = stripped.lower()
#             if any(kw in lower for kw in [
#                 'previous context', 'user ', 'assistant', 'this could',
#                 'option', 'they are', 'the user is', 'acknowledge', 'since an',
#                 'link the greeting', 'testing', 'get attention', 'start new',
#                 'contextual', 'simple'
#             ]):
#                 continue
#         cleaned.append(line)

#     result = '\n'.join(cleaned).strip()
#     if not result:
#         return original  # fallback if we stripped everything
#     return result

def _strip_reasoning(text: str) -> str:
    """Remove leaked chain-of-thought / reasoning / inline templates from model output."""
    import re
    if not text:
        return text

    # 1. Strip standard XML thinking blocks (common in newer reasoning models)
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)

    # 2. Fix the inline single-line leak bug
    if text.strip().startswith('*'):
        # Split by the asterisk markers; the real response sits in the final chunk
        parts = text.split('*')
        last_part = parts[-1].strip()
        
        # Strip away any residual quote examples generated by the template leak
        last_part = re.sub(r'^["\'].*?["\']\s*', '', last_part)
        if last_part:
            return last_part.strip()

    # 3. Standard newline-based cleanup fallback
    lines = text.split('\n')
    cleaned = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith('*') or stripped.startswith('-'):
            continue
        cleaned.append(line)

    result = '\n'.join(cleaned).strip()
    return result or text

async def _call_glm(system_prompt: str, user_content: str) -> str:
    """Call GLM primary model with low temperature."""
    response = await glm_client.chat.completions.create(
        model="GLM-4.7-Flash",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ],
        temperature=0.1,  # Lowered from 0.7 to stop structural hallucinations
    )
    return response.choices[0].message.content

# async def _call_glm(system_prompt: str, user_content: str) -> str:
#     """Call GLM primary model. Raises on failure so caller can fallback."""
#     response = await glm_client.chat.completions.create(
#         model="GLM-4.7-Flash",
#         messages=[
#             {"role": "system", "content": system_prompt},
#             {"role": "user", "content": user_content},
#         ],
#         temperature=0.7,
#     )
#     return response.choices[0].message.content


# def _call_gemma(user_content: str) -> str:
#     """Call Gemma 4 as fallback (uses existing google-generativeai package)."""
#     model = _get_gemma_model()
#     response = model.generate_content(
#         [user_content],
#         generation_config={
#             "temperature": 0.7,
#         },
#     )
#     return response.text.strip()
def _call_gemma(user_content: str) -> str:
    """Call Gemma 4 as fallback with low temperature."""
    model = _get_gemma_model()
    response = model.generate_content(
        [user_content],
        generation_config={
            "temperature": 0.1,  # Lowered from 0.7 to enforce consistency
        },
    )
    return response.text.strip()

async def _ask_llm(user_prompt: str, system_prompt_override: str = None) -> str:
    """
    Call LLM with automatic fallback:
      1. Try GLM first
      2. On 429 / connection error → fall back to Gemma 4
      3. Strip any leaked reasoning from output
    """
    sys = system_prompt_override or SYSTEM_PROMPT
    try:
        raw = await _call_glm(sys, user_prompt)
        return _strip_reasoning(raw)
    except Exception as e:
        err_str = str(e)
        if "429" in err_str or "rate" in err_str.lower() or "connection" in err_str.lower():
            print(f"[Chat] GLM hit rate limit/error, falling back to Gemma 4: {e}")
            try:
                # Run sync gemma call in executor to avoid blocking event loop
                import asyncio
                loop = asyncio.get_event_loop()
                raw = await loop.run_in_executor(None, _call_gemma, user_prompt)
                return _strip_reasoning(raw)
            except Exception as gemma_err:
                print(f"[Chat] Gemma fallback also failed: {gemma_err}")
                return "I'm having trouble connecting right now. Please try again in a moment."
        else:
            # Non-recoverable error (bad auth etc), don't retry
            raise


def _is_memory_query(text: str) -> bool:
    """
    Detect if the user is asking about past memories/dates.
    Examples: "what did I see today", "summarize yesterday", "last Monday"
    """
    memory_keywords = [
        "today", "yesterday", "last", "this morning", "this afternoon",
        "this evening", "earlier", "recently", "seen", "saw", "visited",
        "summarize", "summary", "recall", "remember", "history",
        "did i", "have i", "what did", "where did", "who did"
    ]
    text_lower = text.lower()
    return any(kw in text_lower for kw in memory_keywords)


def _parse_time_range(text: str) -> tuple:
    """
    Parse natural language time references into query parameters.
    Returns (date_str, days_back) tuple - one will be None.
    """
    text_lower = text.lower()
    
    # Today
    if "today" in text_lower:
        return (None, 0)  # 0 days back = today
    # Yesterday
    elif "yesterday" in text_lower:
        return (None, 1)
    # Day-of-week patterns
    weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
    for i, day in enumerate(weekdays):
        if day in text_lower:
            # Find the most recent occurrence of this weekday
            today = datetime.now()
            days_since = (today.weekday() - i) % 7
            if days_since == 0:
                days_since = 7  # If same day, go back one week for "last X"
            return (None, days_since)
    # "Last N days/weeks"
    if "last week" in text_lower:
        return (None, 7)
    if "few days" in text_lower:
        return (None, 3)
    
    return (None, 1)  # Default to yesterday


async def handle_chat(
    user_id: str,
    message: str,
    current_description: str = None,
    current_memory_id: str = None,
) -> str:
    """
    Main chat handler. Routes between memory queries and general conversation.
    
    Args:
        user_id: User UUID
        message: User's transcribed text or typed message
        current_description: (Optional) Current image description if user just took a photo
        current_memory_id: (Optional) Memory record ID for the current image
        
    Returns:
        Assistant's response text
    """
    # Save user message to chat history
    save_chat_message(user_id=user_id, role="user", content=message, 
                      memory_id=current_memory_id)
    
    # Check if this is a memory/history query
    if _is_memory_query(message):
        response = await _handle_memory_response(user_id, message)
    elif current_description:
        # User is asking about the current image they just captured
        response = await _handle_image_qa(user_id, message, current_description)
    else:
        # General conversation
        response = await _handle_general_chat(user_id, message)
    
    # Save assistant response to chat history
    save_chat_message(user_id=user_id, role="assistant", content=response,
                      memory_id=current_memory_id)
    
    return response


async def _handle_memory_response(user_id: str, question: str) -> str:
    """Handle questions about past memories (dates, summaries, etc.)."""
    date_str, days_back = _parse_time_range(question)
    memories = get_memories_by_date(user_id, date_str=date_str, days_back=days_back)

    if not memories:
        # Check if we have ANY memories at all
        all_mems = get_recent_memories(user_id, limit=1)
        if not all_mems:
            return "You don't have any memories recorded yet. Take some photos to build your visual diary!"

        time_label = "that time period" if days_back else "today"
        return f"I don't have any memories from {time_label}. Would you like me to check a different date?"

    # Build context from memories
    memory_texts = []
    for m in memories:
        ts = m.get("created_at", "")
        # Parse timestamp to readable format
        try:
            dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
            time_str = dt.strftime("%I:%M %p")
        except:
            time_str = "unknown time"

        desc = m.get("description", "")
        objs = m.get("objects", [])
        obj_labels = [o.get("label", "") for o in objs if isinstance(o, dict)]
        obj_str = f" Objects: {', '.join(obj_labels)}" if obj_labels else ""
        memory_texts.append(f"[{time_str}] {desc}{obj_str}")

    context = "\n".join(memory_texts)

    user_prompt = (
        f"The user is asking about their past experiences.\n\n"
        f"Question: {question}\n\n"
        f"Here are their memory logs:\n{context}\n\n"
        f"Provide a helpful, concise answer."
    )
    return await _ask_llm(user_prompt)


async def _handle_image_qa(user_id: str, question: str, description: str) -> str:
    """Handle when user asks a question about the currently captured image."""
    user_prompt = (
        f"The user just took a photo and here's its AI-generated description:\n\n"
        f"{description}\n\n"
        f"Now the user asks: {question}\n\n"
        f"Answer based on the image description. Be helpful and descriptive."
    )
    return await _ask_llm(user_prompt)


async def _handle_general_chat(user_id: str, message: str) -> str:
    """Handle general conversation not related to images or memories."""
    # Get recent chat history for context
    recent_chats = get_chat_history(user_id, limit=10)

    # Build conversation history as a single prompt for Gemma fallback compatibility
    history_parts = []
    for chat in recent_chats[-8:]:
        role_label = chat.get("role", "user")
        role_name = "User" if role_label == "user" else "Assistant"
        history_parts.append(f"{role_name}: {chat.get('content', '')}")
    history_context = "\n".join(history_parts) if history_parts else ""

    if history_context:
        user_prompt = (
            f"Recent conversation:\n{history_context}\n\n"
            f"User now says: {message}"
        )
    else:
        user_prompt = message

    return await _ask_llm(user_prompt)
